const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');
const getCurrentDate = require('../dateJs')
const fileSchema  = new mongoose.Schema({
    lastModified:{
        type:Number,
        required:false
    },
    name:{
        type:String,
        required:false
    },
    size:{
        type:Number,
        required:false
    },
    type:{
        type:String,
        required:false
    },
    url:{
        type:String,
        required:false
    },
    _key:{
        type:String,
        required:false
    },
    date:{
        type:String,
        required:false,
    },
    fileId:{
        type:String,
        required:false,
    }
})


const CvSchema = new mongoose.Schema({
    address:{
        type:String,
        required:false
    },
    city:{
        type:String,
        required:false
    },
    country:{
        type:String,
        required:false
    },
    description:{
        type:String,
        required:false
    },
    phoneNumber:{
        type:String,
        required:false
    },
    dialCode:{
        type:String,
        required:false
    },
    email:{
        type:String,
        required:false,
        unique:false
    },
    jobPosition:{
        type:String,
        required:false
    },
    lastName:{
        type:String,
        required:false
    },
    name:{
        type:String,
        required:false
    },
    salary:{
        type:Number,
        required:false
    },
    selectedCv:{
        type:fileSchema,
        required:false
    },
    applicationDate:{
        type:String,
        required:false,
    },
    birthday:{
        type:String,
        required:false
    },
    applicationId:{
        type:String,
        required:false,
    },
    applierFirebaseId:{
        type:String,
        required:false
    },
    applierId:{
        type:String,
        required:false
    },
    profileImage:{
        type:String,
        required:false
    },
    age:{
        type:Number,
        required:false
    },
    status:{
        type:Number,
        required:false,
    },
    firstViewedDate:{
        type:String,
        required:false
    },
    confirmedStatus:{
        type:Boolean,
        default:false,
        required:false
    },
    declinedStatus:{
        type:Boolean,
        default:null,
        required:false
    },
    updatedDate:{
        type:String,
        required:false
    }
})

const CvModel = mongoose.model('CvSchema',CvSchema)
module.exports = CvModel